[build]
target = "avr-specs/avr-atmega2560.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 57600 -P /dev/tty.usbmodem101"

[unstable]
build-std = ["core"]

[net]
git-fetch-with-cli = true